version: '3.4'

services:
  openweathermapapi:
    image: ${DOCKER_REGISTRY-}openweathermapapi
    build:
      context: .
      dockerfile: OpenWeatherMapApi/Dockerfile
  react-redux-weather:
    image: ${DOCKER_REGISTRY-}react-redux-weather
    build:
      context: .
      dockerfile: react-redux-weather/Dockerfile
